package forms;



import com.itextpdf.io.font.Pfm2afm;


import com.itextpdf.layout.element.IBlockElement;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;

import com.itextpdf.text.pdf.PdfWriter;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;

import java.io.FileReader;
import java.io.IOException;
import java.io.InputStream;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;

import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.ss.usermodel.WorkbookFactory;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author osmar
 */
public class Compras extends javax.swing.JFrame {

    /**
     * Creates new form Compras
     */
    public int facturasT;
    public int facturasV;
    public int facturasA;
    public double montoT;
    public double ivaT;
    public double idpT;
    public double totalT;
    public double montoD;
    public double ivaD;
    public double idpD;
    public double totalD;
    
    public int notasC;
    public double montoNC;
    public double ivaNC;
    public int notasA;
    public double montoNA;
    public int peqC;
    public double montopeqC;
    
    DefaultTableModel model= new DefaultTableModel(){
                @Override
                public boolean isCellEditable(int row, int column) {
                    if(column==18){
                        return true;
                    }
                    else{
                        return false;
                    }
                }
                
                
            };
    public Compras() {
        initComponents();
        setLocationRelativeTo(null);
        
            jTable1.setModel(model);
            
            model.addColumn("Fecha");
            model.addColumn("No. Dte");
            model.addColumn("Nit");
            model.addColumn("Nombre Proveedor");
            model.addColumn("Monto");
            model.addColumn("IVA");
            model.addColumn("IDP");
            model.addColumn("Monto Total");
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jTextField14 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clictable(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\osmar\\Documents\\Compras Ventas\\CompraVentas\\src\\main\\sources\\images\\7 (1).png")); // NOI18N
        jButton3.setText("Eliminar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon("C:\\Users\\osmar\\Documents\\Compras Ventas\\CompraVentas\\src\\main\\sources\\images\\5 (1).jpg")); // NOI18N
        jButton4.setText("Agregar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon("C:\\Users\\osmar\\Documents\\Compras Ventas\\CompraVentas\\src\\main\\sources\\images\\6 (1).png")); // NOI18N
        jButton5.setText("Modificar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("Total Facturas");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setText("Vigentes");

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setText("Anuladas");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Monto total:");

        jTextField4.setEditable(false);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("IVA total:");

        jTextField5.setEditable(false);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("IDP total:");

        jTextField6.setEditable(false);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Total:");

        jTextField7.setEditable(false);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("Fecha:");

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setText("No. DTE:");

        jTextField8.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextField8.setEnabled(false);

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setText("Nit:");

        jTextField9.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextField9.setEnabled(false);

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setText("Nombre:");

        jTextField10.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextField10.setEnabled(false);

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel12.setText("Total Factura:");

        jTextField11.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextField11.setEnabled(false);
        jTextField11.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                calcularIVA(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel13.setText("IVA:");

        jTextField12.setEditable(false);
        jTextField12.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextField12.setEnabled(false);

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel14.setText("IDP:");

        jTextField13.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextField13.setEnabled(false);

        jCheckBox1.setText("Ingreso manual");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jTextField14.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField14KeyTyped(evt);
            }
        });

        jLabel15.setText("Filtrar:");

        jMenu1.setText("Archivo");

        jMenuItem1.setIcon(new javax.swing.ImageIcon("C:\\Users\\osmar\\Documents\\Compras Ventas\\CompraVentas\\src\\main\\sources\\images\\3 (1).jpg")); // NOI18N
        jMenuItem1.setText("Cargar Archivo");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setIcon(new javax.swing.ImageIcon("C:\\Users\\osmar\\Documents\\Compras Ventas\\CompraVentas\\src\\main\\sources\\images\\4 (1).png")); // NOI18N
        jMenuItem2.setText("Generar PDF Documentos Externos");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setIcon(new javax.swing.ImageIcon("C:\\Users\\osmar\\Documents\\Compras Ventas\\CompraVentas\\src\\main\\sources\\images\\xls (1).png")); // NOI18N
        jMenuItem3.setText("Generar Excel Libro Compras");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel5))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel9)
                                                .addGap(18, 18, 18)
                                                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                                                .addComponent(jLabel14)
                                                .addGap(18, 18, 18)
                                                .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jTextField10))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jCheckBox1)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel12)
                                                .addComponent(jLabel10)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextField9)
                                            .addComponent(jTextField11, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(327, 327, 327)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                                            .addComponent(jLabel8))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(3, 3, 3)))))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4)
                            .addComponent(jButton5)
                            .addComponent(jButton3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9)
                                .addComponent(jLabel10)
                                .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14)
                        .addComponent(jCheckBox1))
                    .addComponent(jLabel13)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try{
            int fila=jTable1.getSelectedRow();
            ivaT-=Double.parseDouble(jTable1.getValueAt(fila, 5).toString());
            idpT-=Double.parseDouble(jTable1.getValueAt(fila, 6).toString());
            totalT-=Double.parseDouble(jTable1.getValueAt(fila, 7).toString());
            montoT-=Double.parseDouble(jTable1.getValueAt(fila, 4).toString());
            model.removeRow(fila);
            JOptionPane.showMessageDialog(null, "Eliminado correctamente", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
            facturasT--;
            facturasV--;
            jTextField1.setText(Integer.toString(facturasT));
            jTextField2.setText(Integer.toString(facturasV));
            jTextField3.setText(Integer.toString(facturasA));
            jTextField4.setText(Double.toString(Math.round(montoT*100)/100d));
            jTextField5.setText(Double.toString(Math.round(ivaT*100)/100d));
            jTextField6.setText(Double.toString(Math.round(idpT*100)/100d));
            jTextField7.setText(Double.toString(Math.round(totalT*100)/100d));
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error al eliminar datos", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here: jDateChooser1.getDate()!=null|
        try{
        if(jDateChooser1.getDate().toString()!="" |jTextField8.getText()!=""|jTextField9.getText()!=""|jTextField10.getText()!=""|jTextField11.getText()!=""|jTextField12.getText()!=""|jTextField13.getText()!=""){
            Date date=jDateChooser1.getDate();
            DateFormat dateformat=new SimpleDateFormat("yyyy-MM-dd");
            String fecha=dateformat.format(date);
            String nodte=jTextField8.getText();
            String nit=jTextField9.getText();
            String nombre=jTextField10.getText();
            double total=Double.parseDouble(jTextField11.getText());
            double iva=Double.parseDouble(jTextField12.getText());
            double idp=Double.parseDouble(jTextField13.getText());
            
            Object[] arr=new Object[8];
            double monto=total-idp-iva;
            montoT+=Math.round(monto*100)/100d;
            ivaT+=Math.round(iva*100)/100d;
            idpT+=Math.round(idp*100)/100d;
            totalT+=Math.round(total*100)/100d;
            arr[0]=fecha;
            arr[1]=nodte;
            arr[2]=nit;
            arr[3]=nombre;
            arr[4]=montoT;
            arr[5]=iva;
            arr[6]=idp;
            arr[7]=total;
            model.addRow(arr);
            facturasV++;
            facturasT=facturasA+facturasV;
            jTextField1.setText(Integer.toString(facturasT));
            jTextField2.setText(Integer.toString(facturasV));
            jTextField3.setText(Integer.toString(facturasA));
            jTextField4.setText(Double.toString(Math.round(montoT*100)/100d));
            jTextField5.setText(Double.toString(Math.round(ivaT*100)/100d));
            jTextField6.setText(Double.toString(Math.round(idpT*100)/100d));
            jTextField7.setText(Double.toString(Math.round(totalT*100)/100d));
            jTextField8.setText("");
            jTextField9.setText("");
            jTextField10.setText("");
            jTextField11.setText("");
            jTextField12.setText("");
            jTextField13.setText("");
            jDateChooser1.setDate(null);
            JOptionPane.showMessageDialog(null, "Agregado correctamente", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
            
            
        }else{
            JOptionPane.showMessageDialog(null, "Faltan datos ", "Error", JOptionPane.ERROR_MESSAGE);
        }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Faltan datos ", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        if(jCheckBox1.isSelected()){
            jTextField8.enable(true);
            jTextField9.enable(true);
            jTextField10.enable(true);
            jTextField11.enable(true);
            jTextField12.enable(true);
            jTextField13.enable(true);
            jDateChooser1.enable(true);
            jDateChooser1.isEnabled();
            
        }
        else{
            jTextField8.enable(false);
            jTextField9.enable(false);
            jTextField10.enable(false);
            jTextField11.enable(false);
            jTextField12.enable(false);
            jTextField13.enable(false);
            jDateChooser1.enable(false);
        
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void clictable(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clictable
        // TODO add your handling code here:
        if(evt.getClickCount()==2){
            int fila=jTable1.getSelectedRow();
            String fecha=jTable1.getValueAt(fila, 0).toString();
            String nodte=jTable1.getValueAt(fila, 1).toString();
            String nit=jTable1.getValueAt(fila, 2).toString();
            String nombre=jTable1.getValueAt(fila, 3).toString();
            String iva=jTable1.getValueAt(fila, 5).toString();
            String idp=jTable1.getValueAt(fila, 6).toString();
            String total=jTable1.getValueAt(fila, 7).toString();
            montoD=Double.parseDouble(jTable1.getValueAt(fila, 4).toString());
            ivaD=Double.parseDouble(iva);
            idpD=Double.parseDouble(idp);
            totalD=Double.parseDouble(total);
            DateFormat dateformat=new SimpleDateFormat("yyyy-MM-dd");
            try {
                Date fechaTxt=dateformat.parse(fecha);
                jDateChooser1.setDate(fechaTxt);
            } catch (ParseException ex) {
                Logger.getLogger(Compras.class.getName()).log(Level.SEVERE, null, ex);
            }
           
            jTextField8.setText(nodte);
            jTextField9.setText(nit);
            jTextField10.setText(nombre);
            jTextField12.setText(iva);
            jTextField13.setText(idp);
            jTextField11.setText(total);
            
        }
    }//GEN-LAST:event_clictable

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        int fila=jTable1.getSelectedRow();
        if(fila>=0){
            montoT-=montoD;
            ivaT-=ivaD;
            idpT-=idpD;
            totalT-=totalD;
            Date date=jDateChooser1.getDate();
            DateFormat dateformat=new SimpleDateFormat("yyyy-MM-dd");
            String fecha=dateformat.format(date);
            String nodte=jTextField8.getText();
            String nit=jTextField9.getText();
            String nombre=jTextField10.getText();
            double total=Double.parseDouble(jTextField11.getText());
            double iva=Double.parseDouble(jTextField12.getText());
            double idp=Double.parseDouble(jTextField13.getText());
            double monto=total-idp-iva;
            montoT+=Math.round(monto*100)/100d;
            ivaT+=Math.round(iva*100)/100d;
            idpT+=Math.round(idp*100)/100d;
            totalT+=Math.round(total*100)/100d;
            jTextField4.setText(Double.toString(Math.round(montoT*100)/100d));
            jTextField5.setText(Double.toString(Math.round(ivaT*100)/100d));
            jTextField6.setText(Double.toString(Math.round(idpT*100)/100d));
            jTextField7.setText(Double.toString(Math.round(totalT*100)/100d));
            jTable1.setValueAt(fecha, fila, 0);
            jTable1.setValueAt(nodte, fila, 1);
            jTable1.setValueAt(nit, fila, 2);
            jTable1.setValueAt(nombre, fila, 3);
            jTable1.setValueAt(monto, fila, 4);
            jTable1.setValueAt(iva, fila, 5);
            jTable1.setValueAt(idp, fila, 6);
            jTable1.setValueAt(total, fila, 7);
            JOptionPane.showMessageDialog(null, "Modificado correctamente", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
            jTextField8.setText("");
            jTextField9.setText("");
            jTextField10.setText("");
            jTextField11.setText("");
            jTextField12.setText("");
            jTextField13.setText("");
        }
        else{
            JOptionPane.showMessageDialog(null, "No ha escodido ningun dato", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void calcularIVA(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_calcularIVA
        // TODO add your handling code here:
        double iva=Math.round(Double.parseDouble(jTextField11.getText())/1.12*0.12*100)/100d;
        jTextField12.setText(Double.toString(iva));
    }//GEN-LAST:event_calcularIVA

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        JFileChooser fileC= new JFileChooser();
        /*FileNameExtensionFilter fileFilter =new FileNameExtensionFilter("Excel archives",".xls");
        fileC.setFileFilter(fileFilter);*/
        fileC.showOpenDialog(fileC);
        try{
            facturasA=0;
            facturasT=0;
            facturasV=0;
            montoT=0;
            ivaT=0;
            String ruta=fileC.getSelectedFile().getAbsolutePath();
            File archivo = new File(ruta);
            InputStream inp=new FileInputStream(archivo);
            Workbook book=WorkbookFactory.create(inp);
            Sheet sheet=book.getSheetAt(0);
            int iRow=1;
            Row row=sheet.getRow(iRow);
            
           
            while(row!=null){
                Cell fechaR =row.getCell(0);
                String f=fechaR.getStringCellValue();
                String fecha=f.substring(0,10);
                
                Cell nodteR =row.getCell(4);
                String nodte=nodteR.getStringCellValue();
                
                Cell nitR =row.getCell(5);
                String nit=nitR.getStringCellValue();
                
                Cell nombreR =row.getCell(6);
                String nombre=nombreR.getStringCellValue();
                
                Cell montoTR =row.getCell(14);
                double montoTotal=Math.round(montoTR.getNumericCellValue()*100)/100d;
                Cell estadoR =row.getCell(15);
                String estado=estadoR.getStringCellValue();
                
                Cell ivaR =row.getCell(18);
                double iva=Math.round(ivaR.getNumericCellValue()*100)/100d;
                
                
                Cell idpr =row.getCell(19);
                double idp=Math.round(idpr.getNumericCellValue()*100)/100d;
                Cell tipoFR=row.getCell(2);
                String tipoF=tipoFR.getStringCellValue();
                
                if(estado.equalsIgnoreCase("Vigente")&((tipoF.equals("FACT"))|(tipoF.equals("FCAM")))){
                    facturasV++;
                    
                    double monto=Math.round((montoTotal-iva-idp)*100)/100d;
                    
                    
                    Object[] arr=new Object[8];
                    montoT+=Math.round(monto*100)/100d;
                    ivaT+=Math.round(iva*100)/100d;
                    idpT+=Math.round(idp*100)/100d;
                    totalT+=Math.round(montoTotal*100)/100d;
                    arr[0]=fecha;
                    arr[1]=nodte;
                    arr[2]=nit;
                    arr[3]=nombre;
                    arr[4]=monto;
                    arr[5]=iva;
                    arr[6]=idp;
                    arr[7]=montoTotal;
                    model.addRow(arr);
                    
                }else if(!estado.equalsIgnoreCase("Vigente")){
                    facturasA++;
                }else if (tipoF.equals("FPEQ")){
                    peqC++;
                    montopeqC+=montoTotal;
                }else if(tipoF.equals("NABN")){
                    notasA++;
                    montoNA+=montoTotal;
                }else if(tipoF.equals("NCRE")){
                    notasC++;
                    montoNC+=montoTotal;
                    ivaNC+=iva;
                }
                
                iRow++;
                row=sheet.getRow(iRow);
            }
            facturasT=facturasA+facturasV;
            jTextField1.setText(Integer.toString(facturasT));
            jTextField2.setText(Integer.toString(facturasV));
            jTextField3.setText(Integer.toString(facturasA));
            jTextField4.setText(Double.toString(Math.round(montoT*100)/100d));
            jTextField5.setText(Double.toString(Math.round(ivaT*100)/100d));
            jTextField6.setText(Double.toString(Math.round(idpT*100)/100d));
            jTextField7.setText(Double.toString(Math.round(totalT*100)/100d));
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error en cargar el archivo","Error", JOptionPane.ERROR_MESSAGE); 
        }
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        try {
            JFileChooser guardar=new JFileChooser();
            guardar.showSaveDialog(null);
            guardar.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
            File archivo = guardar.getSelectedFile();
            String rute=archivo.toString();
            Document document=new Document(PageSize.A4.rotate());
            PdfWriter pdfwriter=PdfWriter.getInstance(document,new FileOutputStream(rute+".pdf"));
            document.open();
            Paragraph titulo=new Paragraph("Reporte de otros documentos");
            titulo.setAlignment(1);
            Paragraph n1=new Paragraph("Documento: Notas de credito");
            double montoCre=Math.round((montoNC/1.12*100)/100d);
            
            Paragraph n1_0=new Paragraph("Total de documentos: "+Integer.toString(notasC)+"\t Monto: Q"+montoCre+"\t IVA: Q"+Math.round(ivaNC*100)/100d+"\t Total: Q"+Math.round(montoNC*100)/100d);
            Paragraph n2=new Paragraph("Documento: Nota de abono");
            Paragraph n1_1=new Paragraph("Total de documentos: "+Integer.toString(notasA)+"\t Total: Q"+Math.round(montoNA*100)/100d);
            Paragraph n3=new Paragraph("Documento: Facturas Pequeños Contribuyentes");
            Paragraph n1_2=new Paragraph("Total de documentos: "+Integer.toString(peqC)+"\t Total: Q"+Math.round(montopeqC*100)/100d);
          
            
            document.add(titulo);
            document.add(n1);
            document.add(n1_0);
            document.add(n2);
            document.add(n1_1);
            document.add(n3);
            document.add(n1_2);
            document.close();
            pdfwriter.close();
            JOptionPane.showMessageDialog(null, "Se creó el documento correctamente", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
            
            
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Error en la acción", "Mensaje", JOptionPane.ERROR_MESSAGE);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Error en la acción", "Mensaje", JOptionPane.ERROR_MESSAGE);
        } catch (DocumentException ex) {
            JOptionPane.showMessageDialog(null, "Error en la acción", "Mensaje", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        try {
            JFileChooser chooser=new JFileChooser();
            chooser.showSaveDialog(null);
            chooser.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
            String ruta=chooser.getSelectedFile().toString().concat(".xls");
            File archivo=new File(ruta);
            if(archivo.exists()){
                archivo.delete();
            }
            archivo.createNewFile();
            Workbook book=new HSSFWorkbook();
            FileOutputStream arc=new FileOutputStream(archivo);
            Sheet sheet=book.createSheet("Compras");
            
            for(int f=0;f<jTable1.getRowCount();f++){
                Row fila=sheet.createRow(f);
                for(int c=0;c<jTable1.getColumnCount();c++){
                    Cell celda=fila.createCell(c);
                    celda.setCellValue(jTable1.getValueAt(f, c).toString());
                }
            }
            book.write(arc);
            arc.close();
            JOptionPane.showMessageDialog(null, "Se creó el documento correctamente", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Error en la acción", "Mensaje", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed
    TableRowSorter trs;
    private void jTextField14KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField14KeyTyped
        // TODO add your handling code here:
        
        jTextField14.addKeyListener(new KeyAdapter(){
            @Override
            public void keyReleased(KeyEvent e) {
                trs.setRowFilter(RowFilter.regexFilter(jTextField14.getText(), 2));
            }
            
        });
        trs=new TableRowSorter(model);
        jTable1.setRowSorter(trs);
    }//GEN-LAST:event_jTextField14KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Compras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Compras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Compras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Compras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Compras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JCheckBox jCheckBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
